ALTER TABLE prospects ADD COLUMN price NUMERIC NULL;
ALTER TABLE prospects ADD COLUMN realtor BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE prospects ADD COLUMN floor INTEGER NULL;
ALTER TABLE prospects ADD COLUMN property_tax NUMERIC NULL;
ALTER TABLE prospects ADD COLUMN building_fees NUMERIC NULL;
ALTER TABLE prospects ADD COLUMN realtor_fee NUMERIC NULL;
ALTER TABLE prospects ADD COLUMN floor_plan_url TEXT NULL;
ALTER TABLE prospects ADD COLUMN video_url TEXT NULL;
